# Generated by Django 5.0.2 on 2024-02-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=150)),
                ('groupOwnerId', models.CharField(max_length=50)),
                ('groupPassCode', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
