# Generated by Django 5.0.2 on 2024-02-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ownerdetails_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='groupOwnerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ownerdetails'),
        ),
    ]
