# Generated by Django 5.0.2 on 2024-02-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_groups_groupownerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='groupOwnerId',
            new_name='groupOwner',
        ),
    ]
